'use strict';
const $=id=>document.getElementById(id);
const KEY='onde_estacionei_v1', HIST='onde_estacionei_history_v1';
let current=null, photo=null, capturedGps=null, watchId=null, heading=null;
const read=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}};
const persist=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{alert('Armazenamento do navegador cheio ou bloqueado. Tente remover a foto ou liberar espaço.');return false}};
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=iso=>new Date(iso).toLocaleString('pt-BR',{dateStyle:'medium',timeStyle:'short'});
const switchTab=tab=>{document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==tab);if(tab==='find')renderFind();if(tab==='history')renderHistory()};
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
function renderHero(){current=read(KEY,null);$('heroTitle').textContent=current?(current.place||'Meu estacionamento'):'Nenhum estacionamento salvo';$('heroSubtitle').textContent=current?`Salvo em ${fmtDate(current.savedAt)} · Toque em Encontrar carro.`:'Estacionou? Registre sua vaga em segundos.';if(current){$('heroTags').innerHTML=`<span>🅿️ ${safe(current.floor||'Piso não informado')}</span><span>📌 ${safe(current.sector||'Setor não informado')}</span><span>🚙 ${safe(current.spot||'Vaga não informada')}</span>`}else{$('heroTags').innerHTML='<span>📍 GPS opcional</span><span>📷 Foto da vaga</span><span>🅿️ Piso e setor</span>'}}
function geoError(e){let message=e.code===1?'Permissão de localização negada. Use a marcação manual.':e.code===2?'GPS indisponível neste local. Use piso, setor e foto.':'Tempo de GPS esgotado. Tente na entrada da garagem.';return message}
function getGps(cb,status){if(!navigator.geolocation){status.textContent='Este navegador não oferece geolocalização.';return}status.textContent='Buscando sua localização...';navigator.geolocation.getCurrentPosition(p=>{let v={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:Math.round(p.coords.accuracy)};cb(v);status.textContent=`GPS capturado (precisão estimada: ±${v.accuracy} m). Se estiver dentro da garagem, confira a marcação manual.`},e=>{status.textContent=geoError(e)},{enableHighAccuracy:true,timeout:14000,maximumAge:0})}
$('gpsBtn').addEventListener('click',()=>getGps(v=>{capturedGps=v},$('gpsStatus')));
$('photoInput').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){alert('Selecione uma imagem válida.');return}const url=URL.createObjectURL(file);const im=new Image();im.onload=()=>{const scale=Math.min(1,1000/Math.max(im.width,im.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.width*scale));canvas.height=Math.max(1,Math.round(im.height*scale));canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);photo=canvas.toDataURL('image/jpeg',.68);$('photoImg').src=photo;$('photoPreview').hidden=false;URL.revokeObjectURL(url)};im.onerror=()=>{URL.revokeObjectURL(url);alert('Não foi possível ler a imagem.')};im.src=url});
$('removePhoto').addEventListener('click',()=>{photo=null;$('photoInput').value='';$('photoPreview').hidden=true});
$('parkingForm').addEventListener('submit',e=>{e.preventDefault();const data={place:$('place').value.trim(),floor:$('floor').value.trim(),sector:$('sector').value.trim(),spot:$('spot').value.trim(),reference:$('reference').value.trim(),notes:$('notes').value.trim(),entrance:$('entrance').value.trim(),elevator:$('elevator').value.trim(),steps:$('steps').value.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,12),gps:capturedGps,photo,savedAt:new Date().toISOString()};if(![data.place,data.floor,data.sector,data.spot,data.reference,data.notes,data.entrance,data.elevator,data.steps.length,data.gps,data.photo].some(Boolean)){alert('Informe pelo menos uma referência ou capture o GPS.');return}if(current&&!confirm('Substituir o estacionamento ativo? Ele continuará disponível no histórico.'))return;if(!persist(KEY,data))return;const history=read(HIST,[]);history.unshift(data);persist(HIST,history.slice(0,20));renderHero();switchTab('find')});
function renderFind(){current=read(KEY,null);$('emptyFind').hidden=!!current;$('savedView').hidden=!current;if(!current){stopWatching();return}$('parkedAt').textContent=`Registrado em ${fmtDate(current.savedAt)}`;$('locName').textContent=current.place||'Estacionamento sem nome';$('locFloor').textContent=current.floor||'—';$('locSector').textContent=current.sector||'—';$('locSpot').textContent=current.spot||'—';$('locRef').textContent=current.reference?'📍 Referência: '+current.reference:'';$('locNotes').textContent=current.notes?'📝 '+current.notes:'';$('locEntrance').textContent=current.entrance?'🚪 Entrada: '+current.entrance:'';$('locElevator').textContent=current.elevator?'🛗 Acesso: '+current.elevator:'';$('savedPhoto').hidden=!current.photo;if(current.photo)$('savedPhoto').src=current.photo;const link=$('mapsLink');link.hidden=!current.gps;if(current.gps)link.href=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(current.gps.lat+','+current.gps.lng)}&travelmode=walking`;if(!current.gps){$('directionPanel').hidden=true;$('guideStatus').textContent='Não foi salvo GPS. Siga o piso, setor, vaga e a foto.'}else{$('guideStatus').textContent=`GPS salvo com precisão estimada ±${current.gps.accuracy} m. Orientação por GPS não identifica pisos nem corredores.`}}
function rad(v){return v*Math.PI/180}function haversine(a,b){const R=6371000;const dlat=rad(b.lat-a.lat),dlon=rad(b.lng-a.lng);const x=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}function bearing(a,b){const dl=rad(b.lng-a.lng),y=Math.sin(dl)*Math.cos(rad(b.lat)),x=Math.cos(rad(a.lat))*Math.sin(rad(b.lat))-Math.sin(rad(a.lat))*Math.cos(rad(b.lat))*Math.cos(dl);return (Math.atan2(y,x)*180/Math.PI+360)%360}
function updatePosition(pos){if(!current?.gps)return;const at={lat:pos.coords.latitude,lng:pos.coords.longitude};const meters=haversine(at,current.gps);$('directionPanel').hidden=false;$('distance').textContent=meters<1000?`${Math.round(meters)} m`:`${(meters/1000).toFixed(1)} km`;$('accuracy').textContent=`Distância em linha reta · GPS atual ±${Math.round(pos.coords.accuracy)} m`;const angle=bearing(at,current.gps)-(heading??0);$('compassArrow').style.transform=`rotate(${angle}deg)`;$('guideStatus').textContent=heading===null?'A seta indica o norte relativo à tela, não a direção real do celular. Use um mapa externo para caminhar.':'Seta aproximada rumo ao ponto GPS salvo. Em garagem coberta, use as referências.'}
function stopWatching(){if(watchId!==null){navigator.geolocation?.clearWatch(watchId);watchId=null}}
function onOrientation(e){const h=typeof e.webkitCompassHeading==='number'?e.webkitCompassHeading:typeof e.alpha==='number'?(360-e.alpha)%360:null;if(h!==null)heading=h}
$('locateMe').addEventListener('click',async()=>{if(!current?.gps){$('guideStatus').textContent='Sem coordenadas salvas. Utilize a referência do piso, setor e a foto.';return}if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){try{if(await DeviceOrientationEvent.requestPermission()==='granted')window.addEventListener('deviceorientation',onOrientation)}catch{}}else window.addEventListener('deviceorientationabsolute',onOrientation);if(!navigator.geolocation){$('guideStatus').textContent='Seu navegador não oferece geolocalização.';return}stopWatching();$('guideStatus').textContent='Localizando você...';watchId=navigator.geolocation.watchPosition(updatePosition,e=>{$('guideStatus').textContent=geoError(e);stopWatching()},{enableHighAccuracy:true,maximumAge:2500,timeout:14000})});
$('finishBtn').addEventListener('click',()=>{if(!confirm('Encerrar estacionamento atual? O registro permanecerá no histórico.'))return;stopWatching();localStorage.removeItem(KEY);current=null;capturedGps=null;photo=null;$('parkingForm').reset();$('photoPreview').hidden=true;$('gpsStatus').textContent='GPS opcional. Em garagem coberta, ele pode falhar ou apontar para outro local.';renderHero();switchTab('save')});
function renderHistory(){const history=read(HIST,[]);$('historyItems').innerHTML=history.length?history.map((v,i)=>`<div class="history-card"><strong>${safe(v.place||'Estacionamento')}</strong><p>${safe(fmtDate(v.savedAt))} · Piso: ${safe(v.floor||'—')} · Setor: ${safe(v.sector||'—')} · Vaga: ${safe(v.spot||'—')}</p><button type="button" data-restore="${i}">Usar este registro</button></div>`).join(''):'<div class="empty">Nenhum registro anterior.</div>';document.querySelectorAll('[data-restore]').forEach(b=>b.addEventListener('click',()=>{const v=history[Number(b.dataset.restore)];if(!v)return;if(!confirm('Usar este registro como estacionamento atual?'))return;if(persist(KEY,v)){renderHero();switchTab('find')}}))}
$('clearHistory').addEventListener('click',()=>{if(confirm('Apagar o histórico deste navegador? O estacionamento atual não será apagado.')){localStorage.removeItem(HIST);renderHistory()}});
if('serviceWorker' in navigator&&window.isSecureContext)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderHero();
